spring:
  application:
    name: Ridesharing
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.ridesharing: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"